kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-api-quarkus
  labels:
    app: todo-api-quarkus
spec:
  paused: true
  replicas: 1
  selector:
    matchLabels:
      app: todo-api-quarkus
  template:
    metadata:
      labels:
        app: todo-api-quarkus
    spec:
      containers:
        - name: todo-api-quarkus
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          imagePullPolicy: Always
          image: dummy-value
          env:
            - name: APP_STAGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-api-quarkus-config
                  key: app.stage-name
          readinessProbe:
            httpGet:
              port: 8080
              path: /q/health/ready
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: todo-api-quarkus
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600